### ISSUE TITLE
WE need all markers/tag for every Config , could you add this please ?

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#36] opened 2019-12-22 08:47 UTC
At moment we have the configs , but not the needed markers (only some)  It would be good if you could add all needed markers for every Config.    Also at some Configs a bit more explanation. Like for example:  For stairs/escalator config ,  how we can do the json for     different levels , with what kind of markers.

**Comment by modair1000** [comment] 2019-12-22 08:47
otherwise we always need to ask you (Joscha)

**Comment by joscha999** [comment] 2019-12-23 00:07
Duplicate of #27

**Closed by joscha999** 2019-12-23 00:07 UTC
