### ISSUE TITLE
PROBLEM - Between 2 textures the game creates automatic black lines (not so good)

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#87] opened 2020-04-07 08:36 UTC
I wanted to create one desk with 3 mods (the textures have no black lines between)  but the game creates them(black lines) automaticly between that 3 textures.   You told me some weeks ago that this not happens , so is that a bug then ?
![image](https://user-images.githubusercontent.com/56348209/78647970-97401c00-78bb-11ea-92ec-e6eaa873f8fe.png)

**Comment by BR146** [comment] 2020-05-23 15:09
I fiddled around with the PO renderer and the underlying atlas texture and was able to remove those lines.

Changing the filter mode of the atlas texture (note: all mod sprites are pointing to the atlas texture) to `Point` does the trick:
`placeableObject.sprites[0].sd.sprite.texture.filterMode = FilterMode.Point;`

![Renderer](https://user-images.githubusercontent.com/65818738/82733791-c4834500-9d16-11ea-86f3-67e63a7dee50.png)

Originally, the game uses bilinear interpolation. At the edges to transparent, the transparent pixels are all black on the atlas (RGBA is 0,0,0,0). Interpolated with the opaque neighbors this gives some kind of black.

This old unity manual document addresses this in some sorts:
[https://docs.unity3d.com/462/Documentation/Manual/HOWTO-alphamaps.html](https://docs.unity3d.com/462/Documentation/Manual/HOWTO-alphamaps.html)
> If the ‘gutters’ (blank areas between UV’s) have colors/transparencies that are very different from the colors inside the UV’d areas, then those colors can ‘bleed’ together which creates seams on the model.

**Comment by joscha999** [comment] 2020-06-20 20:24
Duplicate of #75

**Closed by joscha999** 2020-06-20 20:24 UTC
