### ISSUE TITLE
More different Vending typs (configs)  for more different sale types

### ISSUE THREAD

**Issue by modair1000** [lvgamedev/simairport-modding#19] opened 2019-11-24 12:28 UTC
Pharmacy , Sweets , Coffee , warm food , cold food , flowers , gifts ..........

**Comment by modair1000** [comment] 2019-11-24 12:31
and also  for  mobilephone Sim cards ,

**Comment by joscha999** [comment] 2019-12-20 14:04
Pretty much a duplicate of #5 so closing this one.

**Closed by joscha999** 2019-12-20 14:04 UTC
